[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
client = { path = "../client" }
is-terminal = "0.4.13"
tabled = "0.16.0"
termsize = "0.1.9"
tokio = "1.41.1"
url = "2.5.4"
