[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20.2"
thiserror = "1.0.65"
types = { path = "../types", features = ["display", "math"] }

[dev-dependencies]
parser = { path = "../parser" }
